spring:
  application:
    name: nc-mrbs-web-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  http:
    encoding:
      force: true
  redis:
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-wait: 60s
        max-idle: 100
        min-idle: 50
    timeout: 3s

# tomcat 配置
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8088

# log
logging:
  file: as-mrbs-web-api.log

# 跨域配置
cros:
  allowedOrigins: '*'

# jwt
jwt:
  header: Authorization
  check_index: 352
  check_code: checkCode
  secret: secret_store_ansun_api_2019
  expiration: 604800 #604800=7天
  route:
    authentication:
      path: auth
      refresh: refresh

# dubbo
dubbo:
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
  protocol:
    id: dubbo
    name: dubbo
    port: 21812
    threads: 1000
    status: client
  consumer:
    retries: 0
    timeout: 60000
    check: false



service:
  version:
    mrbs: 1.0.0

